### ISSUE TITLE
User Registration Support

### ISSUE THREAD

**Issue by donnfelker** [jumpstart-pro/example-hotwire-native-rails-backend#15]
Users should be able to sign up via the `/api/v1/users_controller.rb` 

When complete, we need to add the following routes to the path configuration for both platforms:

### iOS
```ruby
{
  patterns: ["/users/sign_up" ],
  properties: {
    flow: "registration"
  }
}
```

### Android
```ruby
  {
    patterns: ["/users/sign_up"],
    properties: {
      uri: "turbo://fragment/users/sign_up",
      context: "modal"
    }
  }
```

**Comment by excid3** [comment]
No longer needed as we're using web auth now 💪
